filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log

processors:
  - add_cloud_metadata: ~

setup.kibana:
  host: 'kibana:5901'
  username: 'elastic'
  password: 'elastic'

output.logstash:
  hosts: ['logstash:5044']