version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
    - ./:/app
  proxy:
    build:
      context: ./proxy
      dockerfile: proxy.Dockerfile
    depends_on:
      - web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./proxy/cert:/cert
    restart: always