version: '3'

services:
  web:
    image: virtudoc/web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
    - ./:/app
    - ./.m2-cache:/root/.m2
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/virtudoc
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: virtudoc
      SMTP_SERVER: email
      SMTP_USERNAME: testuser@dev.local
      SMTP_PASSWORD: testpassword
      SMTP_PORT: 25
  db:
    image: postgres:13.5-alpine
    ports:
      - "55432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 30s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: virtudoc
      POSTGRES_DB: virtudoc
  proxy:
    image: virtudoc/proxy
    build:
      context: ./proxy
      dockerfile: proxy.Dockerfile
    depends_on:
      - web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./proxy/cert:/cert
    restart: always
  email:
    image: rnwood/smtp4dev:3.1.3-ci20211206101
    ports:
      - "3000:80"
volumes:
  dbdata:
