# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

#require 'selenium-webdriver'
require 'rest-client'
require 'json'

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  #@driver = Selenium::WebDriver.for(:chrome)

  config.shared_context_metadata_behavior = :apply_to_host_groups
  config.order = :random
  config.profile_examples = 10
  config.warnings = true
end
