spring:
  application:
    name: web
  datasource:
    url: "jdbc:h2:mem:"
    username: h2user
    password: virtudoc
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true
  mail:
    default-encoding: UTF-8
    host: localhost
    username: fake
    password: fake
    port: 25
    protocol: smtp
    test-connection: false
test:
  integration: false
server:
  port: 8080
logging:
  level:
    root: DEBUG
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false

---
spring:
  profiles: dev-managed
  application:
    name: web
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  mail:
    default-encoding: UTF-8
    host: ${SMTP_SERVER}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    protocol: smtp
    test-connection: true
test:
  integration: true
server:
  port: 8080
logging:
  level:
    root: DEBUG
  file:
    name: /logs/web.log
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: us-east-1
      auto: false
    s3:
      endpoint: ${AWS_ENDPOINT}
    stack:
      auto: false
file:
  bucket: ${AWS_BUCKET}
  endpoint: ${AWS_ENDPOINT}

---
spring:
  profiles: test
  application:
    name: web
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  mail:
    default-encoding: UTF-8
    host: ${SMTP_SERVER}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    protocol: smtp
    test-connection: true
test:
  integration: true
server:
  port: 8080
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: us-east-1
      auto: false
    s3:
      endpoint: ${AWS_ENDPOINT}
    stack:
      auto: false
file:
  bucket: ${AWS_BUCKET}
  endpoint: ${AWS_ENDPOINT}
logging:
  file:
    name: /logs/web.log

---
spring:
  profiles: prod
  application:
    name: web
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: mysql
  mail:
    default-encoding: UTF-8
    host: ${MAILGUN_SMTP_SERVER}
    username: ${MAILGUN_SMTP_LOGIN}
    password: ${MAILGUN_SMTP_PASSWORD}
    port: ${MAILGUN_SMTP_PORT}
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
server:
  port: ${PORT}
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      auto: true
    s3:
      endpoint: ${AWS_ENDPOINT}
    stack:
      auto: false
file:
  bucket: ${AWS_BUCKET}
  endpoint: ${AWS_ENDPOINT}