spring:
  application:
    name: web
  datasource:
    url: jdbc:h2:mem:virtudoc
    username: h2user
    password: virtudoc
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true
  mail:
    default-encoding: UTF-8
    host: localhost
    username: fake
    password: fake
    port: 25
    protocol: smtp
    test-connection: false
test:
  mail: false
server:
  port: 8080
logging:
  level:
    root: DEBUG

---
spring:
  profiles: dev-managed
  application:
    name: web
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  mail:
    default-encoding: UTF-8
    host: ${SMTP_SERVER}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    protocol: smtp
    test-connection: true
test:
  mail: true
server:
  port: 8080
logging:
  level:
    root: DEBUG

---
spring:
  profiles: test
  application:
    name: web
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  mail:
    default-encoding: UTF-8
    host: ${SMTP_SERVER}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    protocol: smtp
    test-connection: true
test:
  mail: true
server:
  port: 8080

---
spring:
  profiles: prod
  application:
    name: web
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: mysql
  mail:
    default-encoding: UTF-8
    host: ${MAILGUN_SMTP_SERVER}
    username: ${MAILGUN_SMTP_LOGIN}
    password: ${MAILGUN_SMTP_PASSWORD}
    port: ${MAILGUN_SMTP_PORT}
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${PORT}