name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.27
        env:
          MYSQL_ROOT_PASSWORD: virtudoc
          MYSQL_DATABASE: virtudoc
        ports: [ '3306:3306' ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Get m2 cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Setup Java 11 JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: 11
      - name: Compile Java source
        run: mvn compiler:testCompile -B -Dmaven.test.skip=true -Dspring-boot.run.arguments=--spring.profiles.active=test -T4 -q
      - name: Run JUnit tests
        run: mvn test -B -T1
        env:
          JDBC_DATABASE_URL: jdbc:mysql://localhost:3306/virtudoc?user=root&password=virtudoc
          JDBC_DATABASE_USERNAME: root
          JDBC_DATABASE_PASSWORD: virtudoc
      - name: Check slug size
        run: echo "Raw slug size of $(du -sh ./ | awk -F '\t' '{print $1}')/500MB (without compression)"
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./target/surefire-reports/*.xml
          report_individual_runs: "true"